# Generated by Django 4.1.7 on 2023-03-10 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendGestiondeFerme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aliment', models.IntegerField()),
                ('nom_aliment', models.CharField(max_length=500)),
                ('quantite_aliment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Approvisionement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_approvisionement', models.IntegerField()),
                ('nom_approvisionneur_approvisionement', models.CharField(max_length=100)),
                ('nombre_depart_approvisionement', models.IntegerField()),
                ('nombre_arriver_approvisionement', models.IntegerField()),
                ('date_approvisionement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Loge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_loge', models.IntegerField()),
                ('nom_loge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicament', models.IntegerField()),
                ('nom_medicament', models.CharField(max_length=100)),
                ('quantite_medicament', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('race_parent', models.CharField(max_length=100)),
                ('poids_parent', models.CharField(max_length=100)),
                ('sexe_parent', models.CharField(max_length=100)),
                ('etat_parent', models.IntegerField()),
                ('id_approvisionement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.approvisionement')),
                ('id_loge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.loge')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_responsable', models.IntegerField()),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('poste_responsable', models.CharField(max_length=200)),
                ('mot_passe_responsable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.IntegerField()),
                ('nom_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sorti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sorti', models.IntegerField()),
                ('nom_client_sorti', models.CharField(max_length=100)),
                ('date_sorti', models.DateField()),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Prise_medicament_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prise_medicament_parent', models.IntegerField()),
                ('date_prise_medicament_parent', models.DateField()),
                ('id_medicament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.medicament')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.parent')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Prise_medicament_enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prise_medicament_enfant', models.IntegerField()),
                ('date_prise_medicament_enfant', models.DateField()),
                ('id_enfant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.parent')),
                ('id_medicament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.medicament')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='id_sorti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.sorti'),
        ),
        migrations.AddField(
            model_name='parent',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.type'),
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enfant', models.IntegerField()),
                ('race_enfant', models.CharField(max_length=100)),
                ('poids_enfant', models.CharField(max_length=100)),
                ('sexe_enfant', models.CharField(max_length=100)),
                ('etat_enfant', models.IntegerField()),
                ('id_approvisionement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.approvisionement')),
                ('id_loge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.loge')),
                ('id_sorti', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.sorti')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.type')),
            ],
        ),
        migrations.AddField(
            model_name='approvisionement',
            name='id_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable'),
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_alimentation', models.DateField()),
                ('quantite', models.IntegerField()),
                ('id_aliment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.aliment')),
                ('id_loge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.loge')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable')),
            ],
        ),
    ]
