# Generated by Django 4.1.7 on 2023-03-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendGestiondeFerme', '0002_aliment_approvisionement_loge_medicament_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animal', models.IntegerField()),
                ('race_animal', models.CharField(max_length=100)),
                ('poids_animal', models.CharField(max_length=100)),
                ('sexe_animal', models.CharField(max_length=100)),
                ('ids_parents_de_animal', models.CharField(max_length=1000)),
                ('ids_enfants_de_animal', models.CharField(max_length=1000)),
                ('etat_animal', models.IntegerField()),
                ('id_approvisionement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.approvisionement')),
                ('id_loge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.loge')),
                ('id_sorti', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.sorti')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.type')),
            ],
        ),
        migrations.CreateModel(
            name='Prise_medicament_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prise_medicament_animal', models.IntegerField()),
                ('date_prise_medicament_animal', models.DateField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.animal')),
                ('id_medicament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.medicament')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BackendGestiondeFerme.responsable')),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id_approvisionement',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id_loge',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id_sorti',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_enfant',
            name='id_enfant',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_enfant',
            name='id_medicament',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_enfant',
            name='id_responsable',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_parent',
            name='id_medicament',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_parent',
            name='id_parent',
        ),
        migrations.RemoveField(
            model_name='prise_medicament_parent',
            name='id_responsable',
        ),
        migrations.DeleteModel(
            name='Enfant',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Prise_medicament_enfant',
        ),
        migrations.DeleteModel(
            name='Prise_medicament_parent',
        ),
    ]
