# Generated by Django 4.1.7 on 2023-03-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendGestiondeFerme', '0003_animal_prise_medicament_animal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='id_responsable',
        ),
    ]
